import React, { useEffect, useState, useRef } from "react";
import axios from "axios";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";

export default function AdminOverviewPage() {
  const [summaries, setSummaries] = useState([]);
  const reportRef = useRef();

  useEffect(() => {
    axios.get("/api/results").then(res => setSummaries(res.data));
  }, []);

  const chartData = summaries.map(e => ({
    name: e.title,
    participationRate: parseFloat(e.participationRate),
  }));

  const generatePDF = async () => {
    const element = reportRef.current;
    const canvas = await html2canvas(element, { scale: 2 });
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");
    const imgWidth = 190;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 10, 10, imgWidth, imgHeight);
    pdf.save("SDCA_Election_Analytics_Report.pdf");
  };

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">📈 SDCA Election Overview</h1>
        <button
          onClick={generatePDF}
          className="bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded-lg"
        >
          🧾 Generate PDF Report
        </button>
      </div>

      <div ref={reportRef}>
        {/* CHART */}
        <div className="flex justify-center mb-8">
          <BarChart width={700} height={350} data={chartData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" />
            <YAxis domain={[0, 100]} />
            <Tooltip />
            <Bar dataKey="participationRate" fill="#00C49F" />
          </BarChart>
        </div>

        {/* TABLE */}
        <table className="w-full border-collapse border text-sm">
          <thead>
            <tr className="bg-gray-100 text-left">
              <th className="border p-2">Election</th>
              <th className="border p-2">Total Eligible</th>
              <th className="border p-2">Total Voted</th>
              <th className="border p-2">Participation Rate</th>
              <th className="border p-2">Top Candidate</th>
              <th className="border p-2">Votes</th>
            </tr>
          </thead>
          <tbody>
            {summaries.map((e, i) => (
              <tr key={i} className="hover:bg-gray-50">
                <td className="border p-2">{e.title}</td>
                <td className="border p-2">{e.totalEligible}</td>
                <td className="border p-2">{e.totalVoted}</td>
                <td className="border p-2 font-semibold">{e.participationRate}%</td>
                <td className="border p-2">{e.topCandidate}</td>
                <td className="border p-2">{e.topVotes}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* FOOTER */}
        <div className="mt-10 text-center text-gray-500 text-sm">
          <p>Generated by SDCA Smart Voting System</p>
          <p>{new Date().toLocaleString()}</p>
        </div>
      </div>
    </div>
  );
}
